version: "3.9"
services:
  db:
    image: postgres:15
    container_name: postgresql-boilerplate
    restart: always
    networks:
      - boilerplate
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boilerplate
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

networks:
  boilerplate:
    driver: bridge
